=== sapk-tb/INF211-XML/xsd/recette.xsd
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:xsd="http://www.w3.org/2000/10/XMLSchema" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.42.57">
    <xs:element name="recette">
        <xs:complexType>
            <xs:all>
                <xs:element name="titre" type="xs:string"/>
                <xs:element name="informations">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="duree">
                                <xs:complexType>
                                    <xs:attribute name="preparation" type="xs:nonNegativeInteger"/> 
                                    <xs:attribute name="cuisson" type="xs:nonNegativeInteger"/>
                                    <xs:attribute name="repos" type="xs:nonNegativeInteger"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="difficulte">
                                <xs:simpleType>
                                    <xs:restriction base="xs:nonNegativeInteger">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="3"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="cout">
                                <xs:simpleType>
                                    <xs:restriction base="xs:nonNegativeInteger">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="3"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="categorie" type="xs:string"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ingredients">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingredient" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="nombre_de_personnes" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="preparation">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="astuces" type="xs:string" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sapk-tb/INF211-XML/xml/Croustillants aux crevettes.xml
<?xml version="1.0" encoding="UTF-8"?>
<recette
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/recette.xsd">
    <titre>Croustillants aux crevettes</titre>
    <informations>
        <!-- Durée exprimée en minutes -->
        <duree preparation = "0"
                       cuisson     = "50"
                       repos       = "0"/>
        <!-- Difficulté de 0 à 3 -->
        <difficulte>1</difficulte>
        <!-- Coût de 0 à 3 -->
        <cout>2</cout>
        <categorie>Entrée| Poisson-Crustacé</categorie>
    </informations>
    <ingredients nombre_de_personnes = "8">
        <ingredient>16 feuilles de brick</ingredient>
        <ingredient>8 crevettes</ingredient>
        <ingredient>1/2 chorizo</ingredient>
        <ingredient>1 avocat</ingredient>
        <ingredient>16 tranches de fromage</ingredient>
        <ingredient>100 g de feta coupée en dés</ingredient>
        <ingredient>100 g de mozzarella</ingredient>
        <ingredient>1 c.à.s d'huile d'olive</ingredient>
        <ingredient>2 c.à.s d'huile</ingredient>
        <ingredient>1 gousse d'ail</ingredient>
        <ingredient>Jus de citron</ingredient>
        <ingredient>1 oeuf battu</ingredient>
        <ingredient>Sel, poivre </ingredient>
    </ingredients>
    <preparation>
        Faire chauffer dans une poêle l'huile, ajouter la gousse d'ail hachée et les crevettes. Saler, poivrer. Faire cuire pendant 3 minutes. Ajouter 1c.à.s de jus de citron et retirer du feu. Décortiquer les crevettes.
        Dans une autre poêle faire chauffer l'huile d'olive et faire revenir le chorizo à feu vif. Ajouter un peu d'eau et laisser cuire pendant quelques minutes. Egoutter et couper en morceaux.

        Découper les feuilles de brick en disques de 20cm de diamètre. Les disposer deux par deux dans des ramequins beurrés. Dorer à l'oeuf battu.

        Enfourner à 180° C pendant 15min. les feuilles doivent devenir dorées et croustillantes.

        Laver, éplucher et dénoyauter l'avocat. Le couper en dés, ajouter le jus de citron aux morceaux d'avocat.

        Remplir les croustillants de tranches de fromage, de dés de feta, de morceaux de mozzarella et d'avocat, de morceaux de chorizo et de crevettes.

        Servir aussitôt. 
    </preparation>
</recette>

=== sapk-tb/INF211-XML/xml/Sorbet aux prunes jaunes.xml
<?xml version="1.0" encoding="UTF-8"?>

<recette
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/recette.xsd">
	<titre>Sorbet aux prunes jaunes</titre>
	<informations>
		<!-- Durée exprimée en minutes -->
		<duree preparation = "0"
			     cuisson     = "35"
			     repos       = "0"/>
		<!-- Difficulté de 0 à 3 -->
		<difficulte>2</difficulte>
		<!-- Coût de 0 à 3 -->
		<cout>2</cout>
		<categorie>Dessert</categorie>
	</informations>
	<ingredients nombre_de_personnes = "4">
    <ingredient>1 kg de prunes jaunes</ingredient>
    <ingredient>80 cl de sirop à 16° B</ingredient>
    <ingredient>Meringue italienne : 4 blancs d'oeufs</ingredient>
    <ingredient>Meringue italienne : 250g de sucre semoule</ingredient>
    <ingredient>Meringue italienne : 8cl d'eau</ingredient>
	</ingredients>
	<preparation>
Laver, dénoyauter les prunes. Les couper en morceaux.

Pocher les morceaux de prunes dans le sirop, cuire lentement pendant 15 minutes. Les égoutter et les mixer.

Réserver au congélateur pendant 2 heures en remuant avec une fourchette à plusieurs reprises.

Préparer la meringue italienne :

Cuire dans un poêlon le sucre et l'eau lentement en remuant avec une écumoire.

Porter à ébullition, écumer, ne plus remuer.

Placer un thermomètre à sucre et cuire au petit boulé (117° à 120° C), le sucre entre les doigts forme une boule molle.

Monter les blancs d'oeufs très fermes.

Verser le sucre en filet sur les blancs en fouettant énergiquement.

Battre jusqu'à complet refroidissement.

Incorporer délicatement la pulpe de prune à la meringue.

Réserver au congélateur pendant une nuit. 
	</preparation>
</recette>

=== sapk-tb/INF211-XML/xml/Mousse de fraises.xml
<?xml version="1.0" encoding="UTF-8"?>

<recette
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xsd/recette.xsd">
	<titre>Mousse de fraises</titre>
	<informations>
		<!-- Durée exprimée en minutes -->
		<duree preparation = "15"
			     cuisson     = "0"
			     repos       = "120"/>
		<!-- Difficulté de 0 à 3 -->
		<difficulte>2</difficulte>
		<!-- Coût de 0 à 3 -->
		<cout>2</cout>
		<categorie>Dessert</categorie>
	</informations>
	<ingredients nombre_de_personnes = "4">
    <ingredient>fraises : 500 g</ingredient>
    <ingredient>lait concentré non sucré 1/2 écrémé : 160 g</ingredient>
    <ingredient>édulcorant : 3 c. à soupe</ingredient>
    <ingredient>citron : 1</ingredient>
    <ingredient>feuille de menthe (pour le décor)</ingredient>
	</ingredients>
	<preparation>
Battez très vivement au fouet électrique le lait concentré jusqu’à ce qu’il devienne mousseux (le lait doit auparavant être bien froid).

Pressez le citron.

Lavez et équeutez les fraises, gardez-en quelques-unes entières pour le décor. Mettez le reste des fraises dans un mixeur avec le jus de citron et l’édulcorant. Mixez le tout et incorporez délicatement ce coulis au lait.

Mélangez bien et versez cette préparation dans des coupelles individuelles que vous placerez au réfrigérateur au moins pendant 2 h.

Avant de servir, décorez de quelques feuilles de menthe et de fraises coupées en deux.
    <!-- L'élément astuces est optionnel -->
    <astuces>
Commentaire nutritionnel : Le lait concentré, qu’il soit entier, écrémé ou ½ écrémé, résulte d’une évaporation sous vide de 60% de l’eau contenue dans le lait. Il est plus énergétique que le lait car tous ses éléments nutritifs sont concentrés. Il est souvent enrichi en vitamines (vitamine D, C et A), et, comme le lait ordinaire, il est riche en calcium (255mg/100g). Dans cette recette, le lait est non sucré et l’édulcorant remplace le sucre pour éviter une montée de la glycémie. Enfin, les fraises apportent également beaucoup de vitamines (notamment de la vitamine C : 60mg/100g) mais aussi des minéraux (fer, calcium et magnésium) et des fibres (2.1g/100g) tout en restant peu énergétiques (35Kcal/100g).
    </astuces>
	</preparation>
</recette>
